version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - .:/app
    command: sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  redis:
    image: redis:7-alpine

  celery:
    build: .
    command: celery -A server worker -l info
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A server beat -l info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  # flower:
  #   image: mher/flower:0.9.7
  #   command: "celery flower"
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 8888:8888
  #   depends_on:
  #     - redis

  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
